[workspace]
resolver = "2"
members = ["crates/tv-ui", "crates/tv-ui-webgl", "crates/tv-ui-web", "crates/tv-app"]

[workspace.package]
version = "0.1.0"
authors = ["Pauras Ranade <Pauras.Ranade@ril.com>"]
edition = "2018"

[workspace.dependencies]
wasm-bindgen = "0.2.84"
js-sys = "0.3.103"
web-sys = "0.3.103"
lru = { version = "0.18", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
