[package]
name = "rs-wasm-tv-app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
tv-ui = { path = "../tv-ui" }
tv-ui-webgl = { path = "../tv-ui-webgl" }
wasm-bindgen.workspace = true
js-sys.workspace = true

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dependencies.web-sys]
workspace = true
features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "EventTarget",
    "Event",
    "KeyboardEvent",
    "CssStyleDeclaration",
    "Performance",
    "HtmlCanvasElement",
    "HtmlVideoElement",
    "HtmlMediaElement",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
